# Generated by Django 2.2.2 on 2019-06-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioesyllabus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='faculty',
            field=models.CharField(default=None, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='part',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
