# Generated by Django 2.2.2 on 2019-06-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioesyllabus', '0004_auto_20190618_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='faculty',
            field=models.CharField(choices=[('BCT', 'BCT'), ('BEX', 'BEX'), ('BCE', 'BCE')], max_length=4),
        ),
        migrations.AlterField(
            model_name='subject',
            name='part',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II')], max_length=2),
        ),
    ]
