# Generated by Django 2.2.2 on 2019-06-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioesyllabus', '0005_auto_20190618_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='part',
            field=models.CharField(choices=[('1', 'I'), ('2', 'II')], max_length=2),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV')], max_length=2),
        ),
    ]
