# Generated by Django 2.2.2 on 2019-06-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioesyllabus', '0006_auto_20190618_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='faculty',
            field=models.CharField(choices=[('BCT', 'BCT'), ('BEI', 'BEI'), ('BCE', 'BCE')], max_length=4),
        ),
    ]
