# Generated by Django 2.2.2 on 2019-06-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('faculty', models.CharField(choices=[('BCT', 'BCT'), ('BEI', 'BEI'), ('BCE', 'BCE')], max_length=4)),
                ('year', models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV')], max_length=2)),
                ('part', models.CharField(choices=[('1', 'I'), ('2', 'II')], max_length=2)),
            ],
        ),
    ]
