# Generated by Django 2.2.2 on 2019-06-21 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ioesyllabus', '0007_auto_20190621_1804'),
        ('ioenotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='note',
            name='part',
        ),
        migrations.RemoveField(
            model_name='note',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='note',
            name='year',
        ),
        migrations.AddField(
            model_name='note',
            name='subject',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ioesyllabus.Subject'),
            preserve_default=False,
        ),
    ]
